"""
File System Watcher for AI Employee
Monitors a "Drop" folder and creates formatted action files in Needs_Action.
Based on the Bronze project format with timestamp naming and markdown creation.
"""

import time
import os
import shutil
from datetime import datetime
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler
import logging

# Set up logging to match your Bronze project format
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

class FilesystemWatcher(FileSystemEventHandler):
    """
    File system watcher that monitors Drop folder and creates action files.
    Matches the format from your Bronze project implementation.
    """

    def __init__(self, watch_dir="Drop", output_dir="Needs_Action"):
        self.watch_dir = watch_dir
        self.output_dir = output_dir

        # Ensure directories exist
        os.makedirs(self.watch_dir, exist_ok=True)
        os.makedirs(self.output_dir, exist_ok=True)

    def on_created(self, event):
        """Handle new files in the Drop folder."""
        if event.is_directory:
            return

        file_path = event.src_path
        filename = os.path.basename(file_path)

        logger.info(f"New file detected: {file_path}")

        try:
            # Process the file
            self.process_file(file_path, filename)

        except Exception as e:
            logger.error(f"Failed to process file {filename}: {str(e)}")

    def process_file(self, file_path, filename):
        """Process a file by creating a formatted action file."""
        # Read file content if it's a text file
        content = ""
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
        except:
            content = f"[Binary file: {filename}]"

        # Create formatted filename with timestamp
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_filename = filename.replace('.', '_').replace(' ', '_')
        action_filename = f"FILE_DROP_{timestamp}_{safe_filename}.md"

        # Create formatted markdown content
        action_content = f"""# File Drop Action

**File:** {filename}
**Dropped At:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Action ID:** FILE_DROP_{timestamp}

## Original Content
```
{content[:500]}{'...' if len(content) > 500 else ''}
```

## Processing Notes
- [ ] Review file content
- [ ] Determine required action
- [ ] Move to appropriate workflow stage

---
*Auto-generated by filesystem_watcher.py*
"""

        # Write action file
        action_path = os.path.join(self.output_dir, action_filename)
        with open(action_path, 'w', encoding='utf-8') as f:
            f.write(action_content)

        # Remove original file
        os.remove(file_path)

        logger.info(f"Created action file: {action_filename}")
        logger.info(f"Processed file: {filename}")

def main():
    """Main function to run the filesystem watcher."""
    # Configuration matching your Bronze project
    WATCH_DIR = "Drop"  # Monitor Drop folder
    OUTPUT_DIR = "Needs_Action"  # Output to Needs_Action

    # Create directories if they don't exist
    os.makedirs(WATCH_DIR, exist_ok=True)
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Initialize watcher
    watcher = FilesystemWatcher(watch_dir=WATCH_DIR, output_dir=OUTPUT_DIR)

    # Set up observer
    observer = Observer()
    observer.schedule(watcher, WATCH_DIR, recursive=False)

    # Log startup message matching your Bronze format
    logger.info("File System Watcher initialized")
    logger.info(f"Monitoring: {WATCH_DIR}")
    logger.info(f"Output: {OUTPUT_DIR}")
    logger.info("Starting file system watcher (checking every 10s)")

    # Start watching
    observer.start()

    try:
        while True:
            time.sleep(10)  # Check every 10 seconds as in your Bronze project
    except KeyboardInterrupt:
        observer.stop()
        logger.info("File system watcher stopped")

    observer.join()

if __name__ == "__main__":
    main()